### ISSUE TITLE
remove node modules from repository 

### ISSUE THREAD

**Issue by RGHANILOO** [JasonWarrenUK/got-my-back#21]
git rm -r --cached node_modules

**Comment by JasonWarrenUK** [comment]
@RGHANILOO wai invalid?

**Comment by RGHANILOO** [comment]
not invalid per se, but not needed in the repo as its balloons the repo size, it gets built in every npm install locally, i have added the node_modules to the .gitignore so after this process it should not get pushed back

**Comment by JasonWarrenUK** [comment]
OH I thought the label meant this _issue_ was invalid

If you want to have the shit scared out of you, check out `docs/FLOW.md`
